name: flutter_tutorials_and_quizzes
description: A new Flutter application.

version: 1.0.42+42

environment:
  sdk: ">=2.5.2 <3.0.0"

analyser:
  enable-experiment:
    - control-flow-collections


dependencies:
  flutter:
    sdk: flutter

  apk_admin: ^1.0.2
  translator: ^0.1.4
  kf_drawer: ^1.1.2
  animated_background: ^1.0.5
  percent_indicator:
  geolocator: ^5.3.2+2
  google_maps_flutter: ^0.5.28+1
  in_app_purchase: ^0.3.4+1
  toast:
  shared_preferences: ^0.5.2
  flutter_app_badger: ^1.1.2
  flutter_phoenix:
  get:
  package_info:
  url_launcher:
  http:
  pimp_my_button:
  sqflite:
  path_provider:
  tflite:
  image_picker:
  share:
  in_app_update:
  spincircle_bottom_bar:
  flutter_staggered_grid_view:
  google_sign_in:
  foldable_sidebar:
  animated_text_kit:
  expandable:
  flutter_colorpicker:
  like_button:
  fancy_bottom_navigation:
  fab_circular_menu:
  curved_navigation_bar:
  rxdart:
  grafpix:
  day_night_time_picker:
  firebase_messaging:
  firebase_admob:
  advance_pdf_viewer:
  google_nav_bar:
  clippy_flutter:
  water_drop:
  cloud_firestore:
  firebase_storage:
  flutter_auth_buttons:
  flutter_facebook_login:
  provider:
  firebase_auth:
  backdrop:
  multi_image_picker:
  flutter_webview_plugin:
  avatar_glow:
  sliding_up_panel:
  widget_with_codeview:
  wave:
  marquee:
  smooth_page_indicator:
  flutter_flip_view:
  flip_card:
  admob_flutter:
  splashscreen:
  flushbar:
  animator:
  chewie:
  audioplayers:
  flutter_local_notifications:
  flutter_spinkit:
  carousel_slider:
  cupertino_icons:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/MoreCodes/ 
    - Images/
    - Images/LifePath/
    - Images/LandingPage/
    - assets/Music/
    - assets/TensorFlow/
    - videos/
    - lib/Codes_FrontEnd/2_Keywords/
    - lib/Codes_FrontEnd/3_Text/
    - lib/Codes_FrontEnd/4_AppBar/
    - lib/Codes_FrontEnd/5_MainBg/
    - lib/Codes_FrontEnd/6_Image/
    - lib/Codes_FrontEnd/7_Buttons/
    - lib/Codes_FrontEnd/8_Toast/
    - lib/Codes_FrontEnd/9_Layouts/
    - lib/Codes_FrontEnd/10_Dialogs/
    - lib/Codes_FrontEnd/11_Divider/
    - lib/Codes_FrontEnd/12_Navigation/
    - lib/Codes_FrontEnd/13_SnBar/
    - lib/Codes_FrontEnd/14_FlushBar/
    - lib/Codes_FrontEnd/15_Card/
    - lib/Codes_FrontEnd/16_TextOverflow/
    - lib/Codes_FrontEnd/17_GestureDetector/
    - lib/Codes_FrontEnd/18_ListView/
    - lib/Codes_FrontEnd/19_TextField/
    - lib/Codes_FrontEnd/20_Footer/
    - lib/Codes_FrontEnd/21_ImageSlider/
    - lib/Codes_FrontEnd/22_Notification/
    - lib/Codes_FrontEnd/23_Switch/
    - lib/Codes_FrontEnd/24_Audio/
    - lib/Codes_FrontEnd/25_VideoPlayer/
    - lib/Codes_FrontEnd/26_SimpleLoader/
    - lib/Codes_FrontEnd/27_Advanced_Loader/
    - lib/Codes_FrontEnd/28_Animation/
    - lib/Codes_FrontEnd/29_Radio/
    - lib/Codes_FrontEnd/30_CheckBox/
    - lib/Codes_FrontEnd/31_Chip/
    - lib/Codes_FrontEnd/32_TabBar/
    - lib/Codes_FrontEnd/33_PageSelector/
    - lib/Codes_FrontEnd/34_Flex/
    - lib/Codes_FrontEnd/35_SelectComboBox/
    - lib/Codes_FrontEnd/36_ExpandableList/
    - lib/Codes_FrontEnd/37_Slider/
    - lib/Codes_FrontEnd/38_Drawer/
    - lib/Codes_FrontEnd/39_SplashScreenLoading/
    - lib/Codes_FrontEnd/40_Admob/
    - lib/Codes_FrontEnd/41_FlipCard/
    - lib/Codes_FrontEnd/42_FlipView/
    - lib/Codes_FrontEnd/43_Stepper/
    - lib/Codes_FrontEnd/44_BottomSheet/
    - lib/Codes_FrontEnd/45_SmoothPageIndicator/
    - lib/Codes_FrontEnd/46_Expandable/
    - lib/Codes_FrontEnd/47_Marquee/
    - lib/Codes_FrontEnd/48_ContainerWaves/
    - lib/Codes_FrontEnd/49_RouteTransition/
    - lib/Codes_FrontEnd/50_Flutter_Syntaxe/
    - lib/Codes_FrontEnd/51_SlidingUpPanel/
    - lib/Codes_FrontEnd/52_Popup_Menu_Button/1_Simple_AppBar_Popup_Menu_Button.dart
    - lib/Codes_FrontEnd/52_Popup_Menu_Button/2_ListTile_Popup_Menu_Button.dart
    - lib/Codes_FrontEnd/53_Hero_Animation/1_Simple_Hero.dart
    - lib/Codes_FrontEnd/53_Hero_Animation/2_Advanced_Hero.dart
    - lib/Codes_FrontEnd/54_AvatarGlow/1_AvatarGlow_1Glow.dart
    - lib/Codes_FrontEnd/54_AvatarGlow/2_AvatarGlow_2Glow.dart
    - lib/Codes_FrontEnd/54_AvatarGlow/3_AvatarGlow_More.dart
    - lib/Codes_FrontEnd/55_DataTable/
    - lib/Codes_FrontEnd/56_WebView/1_WebView_Simple.dart
    - lib/Codes_FrontEnd/57_BackDrop/
    - lib/Codes_FrontEnd/58_Animated_Icon/
    - lib/Codes_FrontEnd/59_TinderSwipe/
    - lib/Codes_FrontEnd/60_ImagePicker/
    - lib/Codes_FrontEnd/61_MultipleImagePicker/
    - lib/Codes_FrontEnd/62_Advance_Pdf_Viewer/
    - lib/Codes_FrontEnd/63_Google_NavBar/1_Google_NavBar.dart
    - lib/Codes_FrontEnd/64_Clippy/
    - lib/Codes_FrontEnd/65_Water_Drop/
    - lib/Codes_FrontEnd/66_DayNightPicker/
    - lib/Codes_FrontEnd/67_GrafPix/
    - lib/Codes_FrontEnd/68_ListScrollWheel/
    - lib/Codes_FrontEnd/69_Dialog_Transition/
    - lib/Codes_FrontEnd/70_Toggle_Button/1_Toggle_Button.dart
    - lib/Codes_FrontEnd/71_Selectable_Text/1_Selectable_Text.dart
    - lib/Codes_FrontEnd/72_GridView/
    - lib/Codes_FrontEnd/73_Curved_Navigation_Bar/
    - lib/Codes_FrontEnd/74_Floating_Action_Button/
    - lib/Codes_FrontEnd/75_ToolTip/1_ToolTip.dart
    - lib/Codes_FrontEnd/76_Back_Detector/1_Back_Detector.dart
    - lib/Codes_FrontEnd/77_Clipping/
    - lib/Codes_FrontEnd/78_Navigation_Rail/
    - lib/Codes_FrontEnd/79_Fancy_Bottom_NavBar/
    - lib/Codes_FrontEnd/80_Color_Picker/
    - lib/Codes_FrontEnd/81_Like_Button/
    - lib/Codes_FrontEnd/82_Sliver_AppBar/
    - lib/Codes_FrontEnd/83_Animated_Text_Kit/1_AnimatedTextKit_TypewriterAnimatedTextKit.dart
    - lib/Codes_FrontEnd/83_Animated_Text_Kit/2_AnimatedTextKit_Rotate.dart
    - lib/Codes_FrontEnd/83_Animated_Text_Kit/3_AnimatedTextKit_Fade.dart
    - lib/Codes_FrontEnd/83_Animated_Text_Kit/4_AnimatedTextKit_Scale.dart
    - lib/Codes_FrontEnd/83_Animated_Text_Kit/5_AnimatedTextKit_Colorize.dart
    - lib/Codes_FrontEnd/83_Animated_Text_Kit/6_AnimatedTextKit_TextLiquidFill.dart
    - lib/Codes_FrontEnd/83_Animated_Text_Kit/7_AnimatedTextKit_Typer.dart
    - lib/Codes_FrontEnd/84_Foldable_SideBar/1_Foldable_SideBar.dart
    - lib/Codes_FrontEnd/Advanced/
    - lib/Codes_FrontEnd/85_Percent_Indicator/
    - lib/Codes_FrontEnd/86_Connectivity/
    - lib/Codes_FrontEnd/87_SpinCircleBottomBar/
    - lib/Codes_FrontEnd/88_Staggered_GridView/
    - lib/Codes_FrontEnd/89_InAppUpdate/
    - lib/Codes_FrontEnd/90_Timer/
    - lib/Codes_FrontEnd/91_Share/
    - lib/Codes_FrontEnd/92_ExitApp/1_ExitApp.dart
    - lib/Codes_FrontEnd/93_TensorFlow/
    - lib/Codes_FrontEnd/94_PimpMyButton/
    - lib/Codes_FrontEnd/95_AnimatedList/
    - lib/Codes_FrontEnd/96_FlutterAppBadger/
    - lib/Codes_FrontEnd/97_InAppPurchase/
    - lib/Codes_FrontEnd/98_PageView_Animation/
    - lib/Codes_FrontEnd/99_AnimatedBackground/
    - lib/Codes_FrontEnd/100_Geolocator/
    - lib/Codes_FrontEnd/101_GoogleMaps/
    - lib/Codes_FrontEnd/102_KF_Drawer/
    - lib/Codes_FrontEnd/103_GoogleTranslator/
    - lib/Codes_FrontEnd/104_ApkAdmin/
    - lib/Codes_BackEnd/Backend_1_SQFlite/
    - lib/Codes_BackEnd/Backend_2_PHP_Http/
    - lib/Codes_BackEnd/Backend_3_FireBase/
    - lib/Codes_BackEnd/Backend_4_FireStore/
    - lib/Codes_BackEnd/Backend_5_FireBase_Admob/
    - lib/Codes_BackEnd/Backend_6_FireBase_Push_Notification/
    - lib/Codes_BackEnd/Backend_7_PhoneVerificationCode/
    - lib/Codes_BackEnd/Backend_8_HTTP_PHP_Auth/
    - lib/Codes_BackEnd/Backend_9_HTTP_CRUD_Img/
    - lib/UsersCode/1_Davi_Contact_List/ContactList.dart
    - lib/_UISamples/UISample_1/UISamples_1.dart
    - lib/_UISamples/UISample_2/UISample_2.dart
    - lib/_UISamples/UISample_3/UISample_3.dart
    - lib/_UISamples/UISample_4/UISample_4.dart
    - lib/_UISamples/UISample_5/UISample_5.dart
    - lib/_UISamples/UISample_6/UISample_6.dart
    - lib/_UISamples/UISample_7/UISample_7.dart
    - lib/_UISamples/UISample_8/UISample_8.dart
    - lib/_UISamples/UISample_9/UISample_9.dart


  fonts:
    - family: Lora
      fonts:
         - asset: fonts/Lora-Bold.ttf
    - family: Crimson Text
      fonts:
         - asset: fonts/CrimsonText-Bold.ttf
    - family: Raleway
      fonts:
         - asset: fonts/Raleway-Bold.ttf
    - family: Lobster
      fonts:
          - asset: fonts/Lobster-Regular.ttf
    - family: PT Mono
      fonts:
          - asset: fonts/PTMono-Regular.ttf




